<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        services
* GENERATION DATE:  15.06.2019
* CLASS FILE:       /vg-user/home/jb/soft/rest/cgen/generated_classes/class.services.php
* FOR MYSQL TABLE:  services
* FOR MYSQL DB:     hsc
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("config/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class services
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $service_id;   // KEY ATTR. WITH AUTOINCREMENT

var $type_of_service;   // (normal Attribute)
var $user_id;   // (normal Attribute)
var $genre_library;   // (normal Attribute)
var $option_diet;   // (normal Attribute)
var $text_info;   // (normal Attribute)
var $date_service;   // (normal Attribute)
var $informed;   // (normal Attribute)
var $date_informed;   // (normal Attribute)
var $closed;   // (normal Attribute)
var $date_closed;   // (normal Attribute)
var $reason_closed;   // (normal Attribute)
var $rate_pacient;   // (normal Attribute)
var $rate_worker;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function services()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getservice_id()
{
return $this->service_id;
}

function gettype_of_service()
{
return $this->type_of_service;
}

function getuser_id()
{
return $this->user_id;
}

function getgenre_library()
{
return $this->genre_library;
}

function getoption_diet()
{
return $this->option_diet;
}

function gettext_info()
{
return $this->text_info;
}

function getdate_service()
{
return $this->date_service;
}

function getinformed()
{
return $this->informed;
}

function getdate_informed()
{
return $this->date_informed;
}

function getclosed()
{
return $this->closed;
}

function getdate_closed()
{
return $this->date_closed;
}

function getreason_closed()
{
return $this->reason_closed;
}

function getrate_pacient()
{
return $this->rate_pacient;
}

function getrate_worker()
{
return $this->rate_worker;
}

// **********************
// SETTER METHODS
// **********************


function setservice_id($val)
{
$this->service_id =  $val;
}

function settype_of_service($val)
{
$this->type_of_service =  $val;
}

function setuser_id($val)
{
$this->user_id =  $val;
}

function setgenre_library($val)
{
$this->genre_library =  $val;
}

function setoption_diet($val)
{
$this->option_diet =  $val;
}

function settext_info($val)
{
$this->text_info =  $val;
}

function setdate_service($val)
{
$this->date_service =  $val;
}

function setinformed($val)
{
$this->informed =  $val;
}

function setdate_informed($val)
{
$this->date_informed =  $val;
}

function setclosed($val)
{
$this->closed =  $val;
}

function setdate_closed($val)
{
$this->date_closed =  $val;
}

function setreason_closed($val)
{
$this->reason_closed =  $val;
}

function setrate_pacient($val)
{
$this->rate_pacient =  $val;
}

function setrate_worker($val)
{
$this->rate_worker =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM services WHERE service_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysqli_fetch_object($result);


$this->service_id = $row->service_id;

$this->type_of_service = $row->type_of_service;

$this->user_id = $row->user_id;

$this->genre_library = $row->genre_library;

$this->option_diet = $row->option_diet;

$this->text_info = $row->text_info;

$this->date_service = $row->date_service;

$this->informed = $row->informed;

$this->date_informed = $row->date_informed;

$this->closed = $row->closed;

$this->date_closed = $row->date_closed;

$this->reason_closed = $row->reason_closed;

$this->rate_pacient = $row->rate_pacient;

$this->rate_worker = $row->rate_worker;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM services WHERE service_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->service_id = ""; // clear key for autoincrement

$sql = "INSERT INTO services ( type_of_service,user_id,genre_library,option_diet,text_info,date_service,informed,date_informed,closed,date_closed,reason_closed,rate_pacient,rate_worker ) VALUES ( '$this->type_of_service','$this->user_id','$this->genre_library','$this->option_diet','$this->text_info','$this->date_service','$this->informed','$this->date_informed','$this->closed','$this->date_closed','$this->reason_closed','$this->rate_pacient','$this->rate_worker' )";
$result = $this->database->query($sql);
$this->service_id = mysqli_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{

$sql = " UPDATE services SET  type_of_service = '$this->type_of_service',user_id = '$this->user_id',genre_library = '$this->genre_library',option_diet = '$this->option_diet',text_info = '$this->text_info',date_service = '$this->date_service',informed = '$this->informed',date_informed = '$this->date_informed',closed = '$this->closed',date_closed = '$this->date_closed',reason_closed = '$this->reason_closed',rate_pacient = '$this->rate_pacient',rate_worker = '$this->rate_worker' WHERE service_id = $id ";

$result = $this->database->query($sql);

}

function getServices($userid) {
   $sql =  "SELECT * FROM services WHERE user_id = $userid ".
           "order by date_service desc;";
   $this->sql = $sql;
   $result = $this->database->query($sql);
   $result = $this->database->result;
   $this->result = $result;
   $row = mysqli_fetch_all($result,MYSQLI_ASSOC);
   return($row);
}


} // class : end

?>
