<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        surveys
* GENERATION DATE:  15.06.2019
* CLASS FILE:       /vg-user/home/jb/soft/rest/cgen/generated_classes/class.surveys.php
* FOR MYSQL TABLE:  surveys
* FOR MYSQL DB:     hsc
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("config/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class surveys
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $survey_id;   // KEY ATTR. WITH AUTOINCREMENT

var $survey_model;   // (normal Attribute)
var $user_id;   // (normal Attribute)
var $date_survey;   // (normal Attribute)
var $answer;   // (normal Attribute)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function surveys()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getsurvey_id()
{
return $this->survey_id;
}

function getsurvey_model()
{
return $this->survey_model;
}

function getuser_id()
{
return $this->user_id;
}

function getdate_survey()
{
return $this->date_survey;
}

function getanswer()
{
return $this->answer;
}

// **********************
// SETTER METHODS
// **********************


function setsurvey_id($val)
{
$this->survey_id =  $val;
}

function setsurvey_model($val)
{
$this->survey_model =  $val;
}

function setuser_id($val)
{
$this->user_id =  $val;
}

function setdate_survey($val)
{
$this->date_survey =  $val;
}

function setanswer($val)
{
$this->answer =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM surveys WHERE survey_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysqli_fetch_object($result);


$this->survey_id = $row->survey_id;

$this->survey_model = $row->survey_model;

$this->user_id = $row->user_id;

$this->date_survey = $row->date_survey;

$this->answer = $row->answer;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM surveys WHERE survey_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->survey_id = ""; // clear key for autoincrement

$sql = "INSERT INTO surveys ( survey_model,user_id,date_survey,answer ) VALUES ( '$this->survey_model','$this->user_id','$this->date_survey','$this->answer' )";
$result = $this->database->query($sql);
$this->survey_id = mysqli_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{

$sql = " UPDATE surveys SET  survey_model = '$this->survey_model',user_id = '$this->user_id',date_survey = '$this->date_survey',answer = '$this->answer' WHERE survey_id = $id ";

$result = $this->database->query($sql);

}

function getSurveys($userid) {
   $sql =  "SELECT * FROM surveys WHERE user_id = $userid ".
           "order by date_survey desc;";
   $this->sql = $sql;
   $result = $this->database->query($sql);
   $result = $this->database->result;
   $this->result = $result;
   $row = mysqli_fetch_all($result,MYSQLI_ASSOC);
   return($row);
}


} // class : end
?>
