<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        incidents
* GENERATION DATE:  15.06.2019
* CLASS FILE:       /vg-user/home/jb/soft/rest/cgen/generated_classes/class.incidents.php
* FOR MYSQL TABLE:  incidents
* FOR MYSQL DB:     hsc
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* -------------------------------------------------------
*
*/

include_once("config/class.database.php");

// **********************
// CLASS DECLARATION
// **********************

class incidents
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************

var $incident_id;   // KEY ATTR. WITH AUTOINCREMENT

var $user_id;   // (normal Attribute)
var $hosp_or_emerg;   // (normal Attribute)
var $date_incident;   // (normal Attribute)
var $incident_title;   // (normal Attribute)
var $other_text;   // (normal Attribute)
var $informed;   // (normal Attribute)
var $date_informed;   // (normal Attribute)
var $closed;   // (normal Attribute)
var $date_closed;   // (normal Attribute)
var $reason_closed;   // (normal Attribute)
var $rate_pacient;   // (normal Attribute)
var $rate_worker;   // (normal Attribute)
var $sql;   // (SQL)

var $database; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function incidents()
{

$this->database = new Database();

}


// **********************
// GETTER METHODS
// **********************


function getincident_id()
{
return $this->incident_id;
}

function getuser_id()
{
return $this->user_id;
}

function gethosp_or_emerg()
{
return $this->hosp_or_emerg;
}

function getdate_incident()
{
return $this->date_incident;
}

function getincident_title()
{
return $this->incident_title;
}

function getother_text()
{
return $this->other_text;
}

function getinformed()
{
return $this->informed;
}

function getdate_informed()
{
return $this->date_informed;
}

function getclosed()
{
return $this->closed;
}

function getdate_closed()
{
return $this->date_closed;
}

function getreason_closed()
{
return $this->reason_closed;
}

function getrate_pacient()
{
return $this->rate_pacient;
}

function getrate_worker()
{
return $this->rate_worker;
}

// **********************
// SETTER METHODS
// **********************


function setincident_id($val)
{
$this->incident_id =  $val;
}

function setuser_id($val)
{
$this->user_id =  $val;
}

function sethosp_or_emerg($val)
{
$this->hosp_or_emerg =  $val;
}

function setdate_incident($val)
{
$this->date_incident =  $val;
}

function setincident_title($val)
{
$this->incident_title =  $val;
}

function setother_text($val)
{
$this->other_text =  $val;
}

function setinformed($val)
{
$this->informed =  $val;
}

function setdate_informed($val)
{
$this->date_informed =  $val;
}

function setclosed($val)
{
$this->closed =  $val;
}

function setdate_closed($val)
{
$this->date_closed =  $val;
}

function setreason_closed($val)
{
$this->reason_closed =  $val;
}

function setrate_pacient($val)
{
$this->rate_pacient =  $val;
}

function setrate_worker($val)
{
$this->rate_worker =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select($id)
{

$sql =  "SELECT * FROM incidents WHERE incident_id = $id;";
$result =  $this->database->query($sql);
$result = $this->database->result;
$row = mysqli_fetch_object($result);

$this->incident_id = $row->incident_id;
$this->user_id = $row->user_id;
$this->hosp_or_emerg = $row->hosp_or_emerg;
$this->date_incident = $row->date_incident;
$this->incident_title = $row->incident_title;
$this->other_text = $row->other_text;
$this->informed = $row->informed;
$this->date_informed = $row->date_informed;
$this->closed = $row->closed;
$this->date_closed = $row->date_closed;
$this->reason_closed = $row->reason_closed;
$this->rate_pacient = $row->rate_pacient;
$this->rate_worker = $row->rate_worker;

}

// **********************
// DELETE
// **********************

function delete($id)
{
$sql = "DELETE FROM incidents WHERE incident_id = $id;";
$result = $this->database->query($sql);

}

// **********************
// INSERT
// **********************

function insert()
{
$this->incident_id = ""; // clear key for autoincrement

$sql = "INSERT INTO incidents ( user_id,hosp_or_emerg,date_incident,incident_title,other_text) VALUES ( $this->user_id,$this->hosp_or_emerg,'$this->date_incident','$this->incident_title','$this->other_text')";
$this->sql = $sql;
$result = $this->database->query($sql);
$this->incident_id = mysqli_insert_id($this->database->link);

}

// **********************
// UPDATE
// **********************

function update($id)
{



$sql = " UPDATE incidents SET  user_id = '$this->user_id',hosp_or_emerg = '$this->hosp_or_emerg',date_incident = '$this->date_incident',incident_title = '$this->incident_title',other_text = '$this->other_text',informed = '$this->informed',date_informed = '$this->date_informed',closed = '$this->closed',date_closed = '$this->date_closed',reason_closed = '$this->reason_closed',rate_pacient = '$this->rate_pacient',rate_worker = '$this->rate_worker' WHERE incident_id = $id ";

$result = $this->database->query($sql);
}

function consultaTit($userid,$hosp,$tit) {
   $sql =  "SELECT * FROM incidents WHERE user_id = $userid and ".
           "hosp_or_emerg = $hosp and closed is NULL and ".
           "DATEDIFF(now(),date_incident) < 5 and ".
           "incident_title like '$tit';";
   $this->sql = $sql;
   $result = $this->database->query($sql);
   $result = $this->database->result;
   $this->result = $result;
   $row = mysqli_fetch_all($result,MYSQLI_ASSOC);
   return($row);
}

function getIncidents($userid) {
   $sql =  "SELECT * FROM incidents WHERE user_id = $userid ".
           "order by date_incident desc;";
   $this->sql = $sql;
   $result = $this->database->query($sql);
   $result = $this->database->result;
   $this->result = $result;
   $row = mysqli_fetch_all($result,MYSQLI_ASSOC);
   return($row);
}

} // class : end

?>
